### ISSUE TITLE
Транслит не пойдет 

### ISSUE THREAD

**Issue by antosha417** [Xelanid/pprog_ermolenko#2]
https://github.com/Xelanid/pprog_ermolenko/blob/6f205bd3c82b1e0b5fb541b1f765f4e196f710e8/structuraris.py#L18
Попробуй зайти на сайт https://translate.yandex.ru/

**Comment by Xelanid** [comment]
2b4fe3e551e916430ee26339e8003c62447e23eb

**Comment by antosha417** [comment]
Field это как поле для ввода, наверное ты хочешь grass

**Comment by Xelanid** [comment]
e869cc3aafbdf6122e9f56856e26c7df4690babe
Да, что-то не подумал, что field - поле для ввода

**Comment by Xelanid** [comment]
.
